version: '3.9'
services:
  web-app-hp:
    build: 
      context: ./docker/
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/
    command: sh -c "npm start"
    ports:
      - "3000:3000"
    stdin_open: true